### ISSUE TITLE
Problem with webhooks

### ISSUE THREAD

**Issue by hillelcoren** [digitickets/omnipay-gocardlessv2#4]
I'm having trouble parsing webhook notifications.

The readme has `parseNotification(getallheaders(), file_get_contents('php://input'), 'MySecurityToken')->send()`, from reviewing the code it looks like it should be: `parseNotification(file_get_contents('php://input'), $_SERVER['HTTP_WEBHOOK_SIGNATURE'])`.

Even with this change the event data isn't loaded though, I get `[{},{},{},{},{},{}]`.

Any ideas? 

Thanks!

**Comment by hillelcoren** [comment]
I've been able to workaround this by verifying the data sent rather than load it

https://developer.gocardless.com/getting-started/partners/staying-up-to-date-with-webhooks/

**Comment by joeHickson** [comment]
Hi Hillel,
Sorry I didn't get to this sooner - been stuck with on a bug. I don't think you need to ->send() on the parse notification / authenticate endpoints - they function less like requests and more like a service that processes there and then.
Does that help?
We have switched to verifying the signature using authenticateNotification and then looping through.
Be warned that the notifications can come in thick and fast - we have received enough notifications to overload their API by responding to them all immediately! You also only have 10 seconds to respond to their webhook request before it considers it failed / timed out - we are in the process of switching ours over to queueing with the following steps:

1. recieve webhook notification
2. validate signature
3. place each event into queue
4. respond with a success (regardless of if the items fail on the queue - our internal queue will have to handle the failures).

You might not hit this problem but we are processing thousands of transactions in one batch which produces big notification files.

It's also worth noting that if you are going down the partner authentication route that you can get multiple organisations in one response file - but again this may not be relevant to you.

Joe
